export const SET_CURRENT_PLACE = "SET_CURRENT_PLACE";
export const SET_PEOPLE = "SET_PEOPLE";
export const SET_TEMPERATURE = "SET_TEMPERATURE";
export const CHANGE_STATUS_FIRE = "CHANGE_STATUS_FIRE"
export const CHANGE_STATUS_ONGOING = "CHANGE_STATUS_ONGOING";
export const CHANGE_STATUS_COMPLETE = "CHANGE_STATUS_COMPLETE";